# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv

# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g., lanes or resequencing of the same biological
# sample).
units: units.tsv

genome: "data/genome/potato_dm_v404_all_pm_un.fasta"

# sequencing adapter
adapter: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTGTTCCTGAGTGTAGATCTCGGTGGTCGCCGTATCATT

params:
    cutadapt-pe: "-q 10 -m 40 -j 8"
    cutadapt-se: "-q 10 -m 40 -j 8"

controlfile: "LOP868-SRR6123032_coverage.bed"

targets:
 - data/dedup/LOP868_004-KFRAG_00003H-dedup-sorted.aln.bam.bai
 - data/dedup/LOP868_064-KFRAG_00028H-dedup-sorted.aln.bam.bai
 - data/dedup/LOP868_305-KFRAG_00092H-dedup-sorted.aln.bam.bai
 - data/dedup/LOP868-SRR6123032-dedup-sorted.aln.bam.bai
 - data/dedup/IVP101-SRR6123183-dedup-sorted.aln.bam.bai
 - data/dedup/PL4-SRR6123031-dedup-sorted.aln.bam.bai
 - data/calls/all-calls.vcf
